USER_ROLE_ADMIN = 'admin'
USER_ROLE_DRIVER = 'driver'
USER_ROLE_GUEST = 'guest'

USER_ROLES = [
    USER_ROLE_ADMIN,
    USER_ROLE_DRIVER,
    USER_ROLE_GUEST,
]

AUTH_TYPE_LOCAL = 'local'
AUTH_TYPE_GOOGLE = 'google'

AUTH_TYPES = [
    AUTH_TYPE_LOCAL,
    AUTH_TYPE_GOOGLE,
]

FUEL_TYPE_PETROL = 'petrol'
FUEL_TYPE_DIESEL = 'diesel'
FUEL_TYPE_ELECTRIC = 'electric'
FUEL_TYPE_HYBRID = 'hybrid'
FUEL_TYPE_GAS = 'gas'

FUEL_TYPES = [
    FUEL_TYPE_PETROL,
    FUEL_TYPE_DIESEL,
    FUEL_TYPE_ELECTRIC,
    FUEL_TYPE_HYBRID,
    FUEL_TYPE_GAS,
]

MIN_PASSWORD_LENGTH = 8
MAX_PHONE_LENGTH = 20
MIN_PHONE_LENGTH = 9
MAX_BIO_LENGTH = 500
MAX_DESCRIPTION_LENGTH = 1000

MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB
ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp']

DEFAULT_RATING = 100.0
MIN_RATING = 0.0
MAX_RATING = 100.0

MIN_EXPERIENCE_YEARS = 0
MAX_EXPERIENCE_YEARS = 100

MIN_CAR_YEAR = 1900

MIN_PASSENGERS = 1
MAX_PASSENGERS = 20

EMAIL_VERIFICATION_TOKEN_EXPIRY = 24 * 60 * 60  # 24 часа в секундах
PASSWORD_RESET_TOKEN_EXPIRY = 1 * 60 * 60  # 1 час в секундах